//! Initialize pack: create config, repomix config, output dir, cursor rule.

use std::path::Path;

use miette::IntoDiagnostic;

use crate::{HypermixConfig, MixConfig};

const CURSOR_RULE_TEMPLATE: &str = r#"---
name: Pack Generated Files
description: This rule helps you understand the codebase generated by appz pack.
globs: {repomix_files_list}
---

# Understanding Your Pack Generated Files

The following files are generated by appz pack: {repomix_files_list}

They contain a structured representation of your code. Use them to understand
overall structure, find related code, and identify patterns."#;

/// Detect source folders (src, lib, etc.) excluding node_modules, .git, etc.
fn find_source_folders(cwd: &Path) -> Vec<String> {
    let exclude: std::collections::HashSet<&str> = [
        "node_modules", ".git", "dist", "build", "target", ".hypermix", ".pack", "test", "tests",
    ]
    .into_iter()
    .collect();

    let mut folders = std::collections::HashSet::new();
    for e in walkdir::WalkDir::new(cwd)
        .max_depth(3)
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| {
            let name = e.file_name().to_string_lossy();
            !exclude.contains(name.as_ref())
        })
        .filter_map(|e| e.ok())
    {
        if e.file_type().is_file() {
            if let Ok(rel) = e.path().strip_prefix(cwd) {
                if let Some(first) = rel.components().next() {
                    let name = first.as_os_str().to_string_lossy();
                    if !exclude.contains(name.as_ref()) {
                        folders.insert(name.into_owned());
                    }
                }
            }
        }
    }
    let mut v: Vec<_> = folders.into_iter().collect();
    v.sort();
    if v.is_empty() {
        v.push("src".to_string());
    }
    v
}

pub fn init(cwd: &Path) -> miette::Result<()> {
    let source_folders = find_source_folders(cwd);
    let includes: Vec<String> = source_folders.iter().map(|f| format!("{}/**/*", f)).collect();

    // 1. Create pack.config.json
    let config_path = cwd.join("pack.config.json");
    let config = HypermixConfig {
        mixes: vec![MixConfig {
            remote: None,
            include: Some(includes.clone()),
            ignore: None,
            output: None,
            repomix_config: Some("repomix.config.json".to_string()),
            extra_flags: Some(vec!["--quiet".to_string()]),
        }],
        silent: Some(false),
        output_path: Some(".pack".to_string()),
    };
    std::fs::write(&config_path, serde_json::to_string_pretty(&config).into_diagnostic()?)
        .into_diagnostic()?;

    // 2. Create repomix.config.json
    let repomix_config = serde_json::json!({
        "output": { "include": includes }
    });
    std::fs::write(
        cwd.join("repomix.config.json"),
        serde_json::to_string_pretty(&repomix_config).into_diagnostic()?,
    )
    .into_diagnostic()?;

    // 3. Create .pack dir
    std::fs::create_dir_all(cwd.join(".pack")).into_diagnostic()?;

    // 4. Create cursor rule
    let rule_dir = cwd.join(".cursor/rules/pack");
    std::fs::create_dir_all(&rule_dir).into_diagnostic()?;
    let output_file = ".pack/codebase.xml";
    let rule = CURSOR_RULE_TEMPLATE.replace("{repomix_files_list}", output_file);
    std::fs::write(rule_dir.join("cursor-rule.mdx"), rule).into_diagnostic()?;

    Ok(())
}
