use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::detect::detect_toolchains;

/// One on-disk directory `appz clean` can remove.
#[derive(Debug, Clone, Serialize)]
pub struct CleanTarget {
    pub path: PathBuf,
    pub toolchain: &'static str,
    pub kind: CleanTargetKind,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CleanTargetKind {
    /// A toolchain's `output_directory` — regenerated by the next build.
    BuildOutput,
    /// A dependency/vendor directory — regenerated by the next install.
    Dependencies,
}

/// Result of actually deleting a set of `CleanTarget`s.
#[derive(Debug, Serialize)]
pub struct CleanReport {
    pub deleted: Vec<CleanTarget>,
    pub failed: Vec<(PathBuf, String)>,
    pub freed_bytes: u64,
}

/// Dependency directories to offer under `--deps`, keyed by `mise_plugin`.
/// Deliberately small: only ecosystems with one canonical, project-local,
/// expensive-to-regenerate dependency directory are listed here. Go's module
/// cache and Java's `.m2` are global (not per-project), so they're excluded.
fn dependency_dirs(mise_plugin: &str) -> &'static [&'static str] {
    match mise_plugin {
        "node" | "bun" => &["node_modules"],
        "python" => &[".venv", "venv"],
        _ => &[],
    }
}

/// Sum of file sizes under `path`, recursing into subdirectories.
/// Best-effort: unreadable entries are skipped rather than failing the walk.
fn dir_size(path: &Path) -> u64 {
    let Ok(entries) = std::fs::read_dir(path) else {
        return 0;
    };
    let mut total = 0u64;
    for entry in entries.flatten() {
        let Ok(metadata) = entry.metadata() else {
            continue;
        };
        if metadata.is_dir() {
            total += dir_size(&entry.path());
        } else {
            total += metadata.len();
        }
    }
    total
}

/// Plan what `appz clean` would remove for the project at `root`, without
/// touching the filesystem. Only directories that actually exist on disk are
/// returned. `include_deps` additionally lists each detected toolchain's
/// dependency directory (see `dependency_dirs`) — off by default because
/// those are expensive to regenerate and shouldn't vanish by accident.
#[must_use]
pub fn plan_clean(root: &Path, include_deps: bool) -> Vec<CleanTarget> {
    let toolchains = detect_toolchains(root).unwrap_or_default();
    let mut targets: Vec<CleanTarget> = Vec::new();
    let mut seen: std::collections::BTreeSet<PathBuf> = std::collections::BTreeSet::new();

    for tc in &toolchains {
        if let Some(out) = tc.output_directory {
            let path = root.join(out);
            if path.is_dir() && seen.insert(path.clone()) {
                let size_bytes = dir_size(&path);
                targets.push(CleanTarget {
                    path,
                    toolchain: tc.name,
                    kind: CleanTargetKind::BuildOutput,
                    size_bytes,
                });
            }
        }

        if include_deps {
            for dep in dependency_dirs(tc.mise_plugin) {
                let path = root.join(dep);
                if path.is_dir() && seen.insert(path.clone()) {
                    let size_bytes = dir_size(&path);
                    targets.push(CleanTarget {
                        path,
                        toolchain: tc.name,
                        kind: CleanTargetKind::Dependencies,
                        size_bytes,
                    });
                }
            }
        }
    }

    targets
}

/// Delete every target's directory. Never panics: a failed removal is
/// recorded in `CleanReport::failed` and the rest of the targets still run.
#[must_use]
pub fn delete_targets(targets: &[CleanTarget]) -> CleanReport {
    let mut deleted = Vec::new();
    let mut failed = Vec::new();
    let mut freed_bytes = 0u64;

    for target in targets {
        match std::fs::remove_dir_all(&target.path) {
            Ok(()) => {
                freed_bytes += target.size_bytes;
                deleted.push(target.clone());
            }
            Err(e) => failed.push((target.path.clone(), e.to_string())),
        }
    }

    CleanReport {
        deleted,
        failed,
        freed_bytes,
    }
}

/// Human-readable byte size (`1536` -> `"1.5 KB"`), binary (1024) units.
#[must_use]
#[allow(clippy::cast_precision_loss)]
pub fn format_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB"];
    if bytes < 1024 {
        return format!("{bytes} B");
    }
    let mut size = bytes as f64;
    let mut unit_idx = 0;
    while size >= 1024.0 && unit_idx < UNITS.len() - 1 {
        size /= 1024.0;
        unit_idx += 1;
    }
    format!("{size:.1} {}", UNITS[unit_idx])
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn test_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("appz-core-clean-test-{}", name));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_plan_clean_finds_rust_target_dir() {
        let dir = test_dir("rust-target");
        fs::write(
            dir.join("Cargo.toml"),
            "[package]\nname = \"test\"\nedition = \"2021\"\n",
        )
        .unwrap();
        fs::create_dir_all(dir.join("target/debug")).unwrap();
        fs::write(dir.join("target/debug/binary"), vec![0u8; 100]).unwrap();

        let targets = plan_clean(&dir, false);
        let target = targets
            .iter()
            .find(|t| t.path == dir.join("target"))
            .expect("target/ should be a clean target");
        assert_eq!(target.kind, CleanTargetKind::BuildOutput);
        assert_eq!(target.toolchain, "Rust");
        assert_eq!(target.size_bytes, 100);
    }

    #[test]
    fn test_plan_clean_skips_missing_output_dir() {
        let dir = test_dir("rust-no-target");
        fs::write(
            dir.join("Cargo.toml"),
            "[package]\nname = \"test\"\nedition = \"2021\"\n",
        )
        .unwrap();

        let targets = plan_clean(&dir, false);
        assert!(
            targets.is_empty(),
            "should not list a build-output dir that doesn't exist on disk"
        );
    }

    #[test]
    fn test_plan_clean_deps_gated_by_flag() {
        let dir = test_dir("node-deps");
        fs::write(dir.join("package.json"), r#"{"name": "test"}"#).unwrap();
        fs::create_dir_all(dir.join("node_modules/left-pad")).unwrap();
        fs::write(dir.join("node_modules/left-pad/index.js"), vec![0u8; 50]).unwrap();

        let without_deps = plan_clean(&dir, false);
        assert!(
            !without_deps
                .iter()
                .any(|t| t.kind == CleanTargetKind::Dependencies),
            "node_modules must not be listed without --deps"
        );

        let with_deps = plan_clean(&dir, true);
        let node_modules = with_deps
            .iter()
            .find(|t| t.path == dir.join("node_modules"))
            .expect("node_modules should be a Dependencies target when include_deps=true");
        assert_eq!(node_modules.kind, CleanTargetKind::Dependencies);
        assert_eq!(node_modules.size_bytes, 50);
    }

    #[test]
    fn test_delete_targets_removes_dir_and_reports_freed_bytes() {
        let dir = test_dir("delete");
        fs::create_dir_all(dir.join("target")).unwrap();
        fs::write(dir.join("target/artifact"), vec![0u8; 42]).unwrap();

        let targets = vec![CleanTarget {
            path: dir.join("target"),
            toolchain: "Rust",
            kind: CleanTargetKind::BuildOutput,
            size_bytes: 42,
        }];

        let report = delete_targets(&targets);

        assert!(!dir.join("target").exists());
        assert_eq!(report.freed_bytes, 42);
        assert_eq!(report.deleted.len(), 1);
        assert!(report.failed.is_empty());
    }

    #[test]
    fn test_format_size() {
        assert_eq!(format_size(0), "0 B");
        assert_eq!(format_size(999), "999 B");
        assert_eq!(format_size(1536), "1.5 KB");
        assert_eq!(format_size(5 * 1024 * 1024), "5.0 MB");
        assert_eq!(format_size(2 * 1024 * 1024 * 1024), "2.0 GB");
    }
}
