use std::collections::BTreeMap;

use crate::detect::DetectedToolchain;

/// Generate mise.toml content from detected toolchains.
/// Deduplicates by mise_plugin, merging framework comments.
fn build_groups<'a>(toolchains: &'a [DetectedToolchain]) -> BTreeMap<&'a str, GroupedEntry<'a>> {
    let mut groups: BTreeMap<&str, GroupedEntry> = BTreeMap::new();
    for tc in toolchains {
        let entry = groups.entry(tc.mise_plugin).or_insert_with(|| GroupedEntry {
            version: tc.version.clone(),
            frameworks: Vec::new(),
        });
        entry.frameworks.extend(tc.frameworks.iter().map(|f| f.name));
    }
    groups
}

fn write_tools_section(groups: &BTreeMap<&str, GroupedEntry>) -> Vec<String> {
    let mut lines = Vec::new();
    lines.push("# Generated by appz".to_string());
    lines.push("# https://mise.jdx.dev".to_string());
    lines.push(String::new());
    lines.push("[tools]".to_string());
    for (plugin, group) in groups {
        let mut line = format!("{plugin} = \"{}\"", group.version);
        if !group.frameworks.is_empty() {
            let names: Vec<&str> = group.frameworks.iter().copied().collect();
            line.push_str(&format!("  # {}", names.join(", ")));
        }
        lines.push(line);
    }
    lines.push(String::new());
    lines
}

pub fn generate(toolchains: &[DetectedToolchain]) -> String {
    let groups = build_groups(toolchains);
    write_tools_section(&groups).join("\n")
}

/// Merge appz-detected toolchains into an existing mise.toml.
///
/// Preserves user-defined sections ([settings], [alias], [env], …) and
/// user-specified tool versions that override appz detection.
pub fn generate_merged(existing: Option<&str>, toolchains: &[DetectedToolchain]) -> String {
    let appz_groups = build_groups(toolchains);
    let appz_plugins: Vec<&str> = appz_groups.keys().copied().collect();

    // Parse existing to extract user tool overrides + other sections
    let mut user_tools: BTreeMap<String, toml::Value> = BTreeMap::new();
    let mut other_sections: BTreeMap<String, toml::Value> = BTreeMap::new();

    if let Some(content) = existing {
        if let Ok(val) = content.parse::<toml::Value>() {
            if let toml::Value::Table(table) = &val {
                for (key, val) in table {
                    if key == "tools" {
                        if let toml::Value::Table(tools) = val {
                            for (tk, tv) in tools {
                                user_tools.insert(tk.clone(), tv.clone());
                            }
                        }
                    } else {
                        other_sections.insert(key.clone(), val.clone());
                    }
                }
            }
        }
    }

    // Merge: appz-detected tools, overridden by user-specified versions
    let mut merged_tools: BTreeMap<String, String> = BTreeMap::new();
    for (plugin, group) in &appz_groups {
        let version = user_tools
            .get(*plugin)
            .and_then(|v| v.as_str().map(String::from))
            .unwrap_or_else(|| group.version.clone());
        merged_tools.insert(plugin.to_string(), version);
    }

    // Preserve user tools that appz didn't detect
    for (plugin, val) in &user_tools {
        if !appz_plugins.contains(&plugin.as_str()) {
            if let Some(version) = val.as_str() {
                merged_tools.insert(plugin.clone(), version.to_string());
            }
        }
    }

    // Build output
    let mut lines = Vec::new();
    lines.push("# Generated by appz".to_string());
    lines.push("# https://mise.jdx.dev".to_string());
    lines.push(String::new());
    lines.push("[tools]".to_string());

    for (plugin, version) in &merged_tools {
        let mut line = format!("{plugin} = \"{version}\"");
        if let Some(entry) = appz_groups.get(plugin.as_str()) {
            if !entry.frameworks.is_empty() {
                let names: Vec<&str> = entry.frameworks.iter().copied().collect();
                line.push_str(&format!("  # {}", names.join(", ")));
            }
        }
        lines.push(line);
    }

    lines.push(String::new());

    // Append non-tools sections
    for (key, val) in &other_sections {
        let section_str = match toml::to_string(val) {
            Ok(s) => s,
            Err(_) => continue,
        };
        // Ensure at least key header if value is empty table
        if val.as_table().map_or(false, |t| t.is_empty()) {
            lines.push(format!("[{key}]"));
            lines.push(String::new());
        } else {
            lines.push(format!("[{key}]"));
            for line in section_str.lines() {
                lines.push(line.to_string());
            }
            lines.push(String::new());
        }
    }

    lines.join("\n")
}

struct GroupedEntry<'a> {
    version: String,
    frameworks: Vec<&'a str>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_tc(plugin: &'static str, version: &str, framework: Option<&'static str>) -> DetectedToolchain {
        DetectedToolchain {
            name: plugin,
            slug: plugin,
            mise_plugin: plugin,
            version: version.to_string(),
            version_files: &[],
            frameworks: framework.map(|f| crate::frameworks::DetectedFramework {
                name: f,
                ecosystem: f,
            }).into_iter().collect(),
            build_command: None,
            install_command: None,
            dev_command: None,
            test_command: None,
            lint_command: None,
            format_command: None,
            output_directory: None,
            env_prefix: None,
        }
    }

    #[test]
    fn test_generate_no_existing() {
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate(&tcs);
        assert!(out.contains("[tools]"));
        assert!(out.contains("node = \"lts\""));
    }

    #[test]
    fn test_generate_merged_keeps_user_override() {
        let existing = Some("[tools]\nnode = \"20\"\n\n[settings]\nalways_keep_download = true\n");
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate_merged(existing, &tcs);
        assert!(out.contains("node = \"20\""), "should keep user version, got:\n{out}");
        assert!(out.contains("[settings]"), "should keep settings section");
        assert!(out.contains("always_keep_download = true"), "should keep settings content");
    }

    #[test]
    fn test_generate_merged_preserves_user_tools() {
        let existing = Some("[tools]\nnode = \"20\"\njava = \"17\"\n");
        let tcs = vec![make_tc("node", "22", None)];
        let out = generate_merged(existing, &tcs);
        assert!(out.contains("node = \"20\""), "user version overrides appz: {out}");
        assert!(out.contains("java = \"17\""), "user-only tool preserved: {out}");
    }

    #[test]
    fn test_generate_merged_empty_existing() {
        let tcs = vec![make_tc("node", "22", None)];
        let out = generate_merged(None, &tcs);
        assert!(out.contains("node = \"22\""));
    }

    #[test]
    fn test_generate_merged_preserves_alias_and_env() {
        let existing = Some("[alias]\nmy-tool = \"1.0\"\n\n[env]\nMY_VAR = \"value\"\n");
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate_merged(existing, &tcs);
        assert!(out.contains("[alias]"));
        assert!(out.contains("my-tool = \"1.0\""));
        assert!(out.contains("[env]"));
        assert!(out.contains("MY_VAR = \"value\""));
    }
}
