use std::collections::BTreeMap;

use crate::detect::DetectedToolchain;

/// Generate mise.toml content from detected toolchains.
/// Deduplicates by mise_plugin, merging framework comments.
fn build_groups<'a>(toolchains: &'a [DetectedToolchain]) -> BTreeMap<&'a str, GroupedEntry<'a>> {
    let mut groups: BTreeMap<&str, GroupedEntry> = BTreeMap::new();
    for tc in toolchains {
        let entry = groups
            .entry(tc.mise_plugin)
            .or_insert_with(|| GroupedEntry {
                version: tc.version.clone(),
                frameworks: Vec::new(),
            });
        entry
            .frameworks
            .extend(tc.frameworks.iter().map(|f| f.name));
    }
    groups
}

fn write_tools_section(groups: &BTreeMap<&str, GroupedEntry>) -> Vec<String> {
    let mut lines = vec![
        "# Generated by appz".to_string(),
        "# https://mise.jdx.dev".to_string(),
        String::new(),
        "[tools]".to_string(),
    ];
    for (plugin, group) in groups {
        let mut line = format!("{plugin} = \"{}\"", group.version);
        if !group.frameworks.is_empty() {
            let names: Vec<&str> = group.frameworks.to_vec();
            line.push_str(&format!("  # {}", names.join(", ")));
        }
        lines.push(line);
    }
    lines.push(String::new());
    lines
}

pub fn generate(toolchains: &[DetectedToolchain]) -> String {
    let groups = build_groups(toolchains);
    write_tools_section(&groups).join("\n")
}

/// Merge appz-detected toolchains into an existing mise.toml's `[tools]`
/// table, leaving every other table/key/comment in the document untouched
/// (uses `toml_edit`, which preserves document structure and comments,
/// instead of a parse-to-value-and-reserialize round trip — that round trip
/// is what corrupts nested tables like `[tasks.build]`).
///
/// A tool the user already pinned in `[tools]` keeps their version; appz
/// only fills in tools it detected that aren't already present. Tools the
/// user has that appz didn't detect are left alone (never touched).
///
/// `existing` is the current mise.toml content, if any. Errs if `existing`
/// is `Some` but fails to parse as TOML — callers must not overwrite a file
/// they can't safely parse.
pub fn generate_merged(
    existing: Option<&str>,
    toolchains: &[DetectedToolchain],
) -> Result<String, String> {
    let groups = build_groups(toolchains);

    let existing = match existing {
        Some(s) => s,
        None => return Ok(write_tools_section(&groups).join("\n")),
    };

    let mut doc = existing
        .parse::<toml_edit::DocumentMut>()
        .map_err(|e| e.to_string())?;

    if doc.get("tools").is_none() {
        doc["tools"] = toml_edit::table();
    }
    let tools = doc["tools"]
        .as_table_mut()
        .ok_or_else(|| "`tools` in mise.toml is not a table".to_string())?;
    for (plugin, group) in &groups {
        if !tools.contains_key(plugin) {
            tools[plugin] = toml_edit::value(group.version.as_str());
        }
    }

    Ok(doc.to_string())
}

struct GroupedEntry<'a> {
    version: String,
    frameworks: Vec<&'a str>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_tc(
        plugin: &'static str,
        version: &str,
        framework: Option<&'static str>,
    ) -> DetectedToolchain {
        DetectedToolchain {
            name: plugin,
            slug: plugin,
            mise_plugin: plugin,
            version: version.to_string(),
            version_files: &[],
            frameworks: framework
                .map(|f| crate::frameworks::DetectedFramework {
                    name: f,
                    ecosystem: f,
                })
                .into_iter()
                .collect(),
            build_command: None,
            install_command: None,
            dev_command: None,
            test_command: None,
            lint_command: None,
            format_command: None,
            output_directory: None,
            env_prefix: None,
        }
    }

    #[test]
    fn test_generate_no_existing() {
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate(&tcs);
        assert!(out.contains("[tools]"));
        assert!(out.contains("node = \"lts\""));
    }

    #[test]
    fn test_generate_merged_keeps_user_override() {
        let existing = Some("[tools]\nnode = \"20\"\n\n[settings]\nalways_keep_download = true\n");
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate_merged(existing, &tcs).unwrap();
        assert!(
            out.contains("node = \"20\""),
            "should keep user version, got:\n{out}"
        );
        assert!(out.contains("[settings]"), "should keep settings section");
        assert!(
            out.contains("always_keep_download = true"),
            "should keep settings content"
        );
    }

    #[test]
    fn test_generate_merged_preserves_user_tools() {
        let existing = Some("[tools]\nnode = \"20\"\njava = \"17\"\n");
        let tcs = vec![make_tc("node", "22", None)];
        let out = generate_merged(existing, &tcs).unwrap();
        assert!(
            out.contains("node = \"20\""),
            "user version overrides appz: {out}"
        );
        assert!(
            out.contains("java = \"17\""),
            "user-only tool preserved: {out}"
        );
    }

    #[test]
    fn test_generate_merged_empty_existing() {
        let tcs = vec![make_tc("node", "22", None)];
        let out = generate_merged(None, &tcs).unwrap();
        assert!(out.contains("node = \"22\""));
    }

    #[test]
    fn test_generate_merged_preserves_alias_and_env() {
        let existing = Some("[alias]\nmy-tool = \"1.0\"\n\n[env]\nMY_VAR = \"value\"\n");
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate_merged(existing, &tcs).unwrap();
        assert!(out.contains("[alias]"));
        assert!(out.contains("my-tool = \"1.0\""));
        assert!(out.contains("[env]"));
        assert!(out.contains("MY_VAR = \"value\""));
    }

    #[test]
    fn test_generate_merged_preserves_nested_task_table_and_comment() {
        let existing = Some("[tasks.build]\nrun = \"echo hi\"\n# keep me\n");
        let tcs = vec![make_tc("node", "lts", None)];
        let out = generate_merged(existing, &tcs).unwrap();
        assert!(
            out.contains("[tasks.build]"),
            "nested table preserved, got:\n{out}"
        );
        assert!(
            out.contains("run = \"echo hi\""),
            "task content preserved:\n{out}"
        );
        assert!(out.contains("# keep me"), "comment preserved:\n{out}");
        assert!(
            out.contains("node = \"lts\""),
            "tools table upserted:\n{out}"
        );
    }

    #[test]
    fn test_generate_merged_rejects_unparseable_existing() {
        let bad = Some("this is not [ valid toml");
        let tcs = vec![make_tc("node", "lts", None)];
        assert!(
            generate_merged(bad, &tcs).is_err(),
            "must not silently discard an unparseable file"
        );
    }
}
