use std::path::Path;

use crate::doctor::DoctorReport;

/// Generate CLAUDE.md content from a DoctorReport.
/// Emits a structured agent instructions file with:
///   - Project summary (detected toolchains + frameworks)
///   - Build / test / dev commands
///   - Environment hints (mise plugins, package manager)
pub fn generate_claude_md(report: &DoctorReport, root: &Path) -> String {
    let mut lines: Vec<String> = Vec::new();

    // ── Header ───────────────────────────────────────────
    let project_name = root
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "project".to_string());
    lines.push(format!("# {project_name}"));
    lines.push(String::new());

    // ── Project summary ──────────────────────────────────
    lines.push("## Project".to_string());
    lines.push(String::new());

    for tc in &report.toolchains {
        let ver = if tc.version.is_empty() || tc.version == "latest" { String::new() } else { format!(" @{}", tc.version) };
        let fw: Vec<&str> = tc.frameworks.iter().map(|f| f.name).collect();
        let fw_str = if fw.is_empty() { String::new() } else { format!(" — {}", fw.join(", ")) };
        lines.push(format!("- **{}{}** — {}{}", tc.name, ver, tc.slug, fw_str));
    }

    if let Some(ref pm) = report.package_manager {
        lines.push(format!("- Package manager: **{pm}**"));
    }

    if let Some(ref mm) = report.monorepo.manager {
        lines.push(format!(
            "- Monorepo: **{mm}** ({} paths)",
            report.monorepo.package_paths.len()
        ));
    }

    lines.push(String::new());

    // ── Commands ─────────────────────────────────────────
    let has_any_cmd = report
        .toolchains
        .iter()
        .any(|t| t.build_command.is_some() || t.dev_command.is_some());

    if has_any_cmd {
        lines.push("## Commands".to_string());
        lines.push(String::new());

        for tc in &report.toolchains {
            let has_build = tc.build_command.is_some();
            let has_dev = tc.dev_command.is_some();
            if !has_build && !has_dev {
                continue;
            }
            lines.push(format!("**{}**", tc.name));
            if let Some(ref b) = tc.build_command {
                lines.push(format!("- Build: `{b}`"));
            }
            if let Some(ref d) = tc.dev_command {
                lines.push(format!("- Dev: `{d}`"));
            }
            lines.push(String::new());
        }
    }

    // ── Environment ──────────────────────────────────────
    let has_mise = report.toolchains.iter().any(|t| !t.mise_plugin.is_empty());
    if has_mise {
        lines.push("## Environment".to_string());
        lines.push(String::new());

        lines.push("### Tools (via mise)".to_string());
        lines.push(String::new());
        for tc in &report.toolchains {
            if !tc.mise_plugin.is_empty() {
                let v = if tc.version.is_empty() || tc.version == "latest" { String::new() } else { format!("@{}", tc.version) };
                lines.push(format!("- `{plugin}{v}`", plugin = tc.mise_plugin));
            }
        }
        lines.push(String::new());
    }

    // ── Agent instructions ───────────────────────────────
    lines.push("## Agent Instructions".to_string());
    lines.push(String::new());
    lines.push("This project uses `appz` to manage toolchains and commands.".to_string());
    lines.push(String::new());
    lines.push("- Setup: `appz install` — detect toolchains + install mise tools + dependencies".to_string());
    lines.push("- Build: `appz build`".to_string());
    lines.push("- Dev: `appz dev`".to_string());
    lines.push("- Diagnose: `appz doctor`".to_string());
    lines.push(String::new());
    lines.push("*Generated by `appz init --claude`*".to_string());
    lines.push(String::new());

    lines.join("\n")
}
